package com.victropolis.euler;

/**
 * Generated programatically by victropolis on 07/04/15.
 */
public class Problem288 extends BaseProblem {
    /*

    Description (from https://projecteuler.net/problem=288):

    For any prime p the number N(p,q) is defined by N(p,q) = ∑n=0 to q Tn*pn with Tn generated by the following
    random number generator:  S0 = 290797 Sn+1 = Sn2 mod 50515093 Tn = Sn mod p   Let Nfac(p,q) be the factorial of N
    (p,q). Let NF(p,q) be the number of factors p in Nfac(p,q).   You are given that NF(3,10000) mod 320=624955285.
     Find NF(61,107) mod 6110

    */
    public static long solve(/* change signature to provide required inputs */) {
        throw new UnsupportedOperationException("Problem288 hasn't been solved yet.");
    }
}

