package com.victropolis.euler;

/**
 * Created by victropolis on 6/12/15.
 */
public class Problem002 extends BaseProblem {
    /*
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
    the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
    even-valued terms.
     */
    public static long solve(long below) {
        long answer = 2;

        for (long term1 = 1, term2 = 2, term3 = term2 + term1;
             term3 < below;
             term1 = term2, term2 = term3, term3 = term2 + term1) {
            if (term3 % 2 == 0) {
                answer += term3;
            }
        }

        return answer;
    }
}
