package com.victropolis.euler;

import org.junit.Assert;
import org.junit.Test;

/**
 * Generated programatically by victropolis on 07/04/15.
 */
public class TestProblem044 {
/*

Description (from https://projecteuler.net/problem=44):

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are: 1, 5, 12, 22,
35, 51, 70, 92, 117, 145, ... It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 =
48, is not pentagonal. Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are
pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

*/

    @Test
    public void test() {
        Assert.assertEquals(5482660L, Problem044.solve(/* change signature to provide required inputs */));
    }
}

