package com.victropolis.euler;

import org.junit.Assert;
import org.junit.Test;

/**
 * Generated programatically by victropolis on 07/04/15.
 */
public class TestProblem045 {
/*

Description (from https://projecteuler.net/problem=45):

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:    Triangle &nbsp; Tn=n(n+1)/2
&nbsp; 1, 3, 6, 10, 15, ...   Pentagonal &nbsp; Pn=n(3n−1)/2 &nbsp; 1, 5, 12, 22, 35, ...   Hexagonal &nbsp; Hn=n
(2n−1) &nbsp; 1, 6, 15, 28, 45, ...    It can be verified that T285 = P165 = H143 = 40755. Find the next triangle
number that is also pentagonal and hexagonal.

*/

    @Test
    public void test() {
        Assert.assertEquals(1533776805L, Problem045.solve(/* change signature to provide required inputs */));
    }
}

