package com.victropolis.euler;

import org.junit.Assert;
import org.junit.Test;

/**
 * Generated programatically by victropolis on 07/04/15.
 */
public class TestProblem061 {
/*

Description (from https://projecteuler.net/problem=61):

Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and
are generated by the following formulae:    Triangle &nbsp; P3,n=n(n+1)/2 &nbsp; 1, 3, 6, 10, 15, ...   Square &nbsp;
 P4,n=n2 &nbsp; 1, 4, 9, 16, 25, ...   Pentagonal &nbsp; P5,n=n(3n−1)/2 &nbsp; 1, 5, 12, 22, 35, ...   Hexagonal
 &nbsp; P6,n=n(2n−1) &nbsp; 1, 6, 15, 28, 45, ...   Heptagonal &nbsp; P7,n=n(5n−3)/2 &nbsp; 1, 7, 18, 34, 55, ...
 Octagonal &nbsp; P8,n=n(3n−2) &nbsp; 1, 8, 21, 40, 65, ...    The ordered set of three 4-digit numbers: 8128, 2882,
 8281, has three interesting properties.  The set is cyclic, in that the last two digits of each number is the first
 two digits of the next number (including the last number with the first). Each polygonal type: triangle (P3,
 127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), is represented by a different number in the set. This
 is the only set of 4-digit numbers with this property.  Find the sum of the only ordered set of six cyclic 4-digit
 numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is
 represented by a different number in the set.

*/

    @Test
    public void test() {
        Assert.assertEquals(28684L, Problem061.solve(/* change signature to provide required inputs */));
    }
}

